language: r
sudo: false
cache: packages
dist: trusty

matrix:
  include:
    - os: linux
      r: release
      env: R_CODECOV=true
    - os: linux
      r: devel
      env: _R_CHECK_LENGTH_1_LOGIC2_=TRUE
    - os: osx
      osx_image: xcode10
      r: oldrel

r_binary_packages:
  - covr

warnings_are_errors: false

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi

env:
   global:
     - R_BUILD_ARGS="--no-manual --no-build-vignettes"
     - R_CHECK_ARGS="--as-cran --no-manual --no-build-vignettes"

notifications:
 email:
   on_success: change
   on_failure: change
